ln -s ~/dotfiles/.bashrc ~/.bashrc
ln -s ~/dotfiles/.vimrc ~/.vimrc
ln -s ~/dotfiles/.vim ~/.vim
ln -s ~/dotfiles/.tmux.conf ~/.tmux.conf
ln -s ~/dotfiles/.tmux ~/.tmux
ln -s ~/dotfiles/.cgdb ~/.cgdb
ln -s ~/dotfiles/.merger.sh ~/.merger.sh
ln -s ~/dotfiles/.diffwrap.sh ~/.diffwrap.sh
ln -s ~/dotfiles/.gitconfig ~/.gitconfig
ln -s ~/dotfiles/.vifm ~/.vifm
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
